//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdHeyna
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrowdHeynaEntities : DbContext
    {
        public CrowdHeynaEntities()
            : base("name=CrowdHeynaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Keyword> Keywords { get; set; }
        public virtual DbSet<Source> Sources { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<UserKeywordTag> UserKeywordTags { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserKeywordTagSuggestion> UserKeywordTagSuggestions { get; set; }
        public virtual DbSet<Tweet> Tweets { get; set; }
    }
}
